### PR TITLE
Update to README.md to add the MathJAX JS

### PR DESCRIPTION
**Pull request by sengopal**
Update to README.md to add the MathJAX JS to support frac and other features.

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi @sengopal. Thank you for the submission. Did you intend to put this under the Markdown section of the README? I ask because the instructions you proposed do not seem to be specific to Markdown.

**Comment by sengopal** [comment]
Ah :) fair point. I encountered this while creating `\frac` in Markdown files. I can change it to a different section if that looks better.

**Comment by justinmayer** [comment]
Well, it's not about whether it *looks* better. If this also applies to ReStructuredText (and I gather that it does), then these instructions should be placed somewhere in the document that is appropriate regardless of which format folks are composing in.

**Comment by sengopal** [comment]
:) you are correct. Thanks for the comment. I have changed the section to be format independent. Hope this looks better.

**Review by justinmayer — APPROVED** [review]
Many thanks for the enhancement, @sengopal 🥇

**Pull request merged**
